### ISSUE TITLE
Re-enable tests

### ISSUE THREAD

**Issue by Fidget-Spinner** [source-academy/py-slang#4]
We need to fix the test and re-enable them.

**Comment by Fidget-Spinner** [comment]
To be clear, the tests are working, we just need some sort of CI.

**Comment by martin-henz** [comment]
@s-kybound do you have a suggestion how we specify CI testing for py-slang? Can we follow scm-slang in this?

**Comment by s-kybound** [comment]
@martin-henz Hi prof, I've integrated dependabot as well as husky into scm-slang. As with js-slang - husky should prevent commits from having poor quality + pushes from having broken code (at least, according to the specifications given by the test cases), while dependabot checks for the quality of code in every PR, be it from a branch or a fork.

Other than the integration tests of scm/py-slang with their respective js-slang parsers or tests for mapping functions etc, both repositories should still manage their own unit tests and code, and so the directories in js-slang that contain both submodules should remain ignored by js-slang coverage/testing

**Comment by Fidget-Spinner** [comment]
I can set up CI, it should just be an ubuntu node runner.
